Autodelete
Popcorn-moe/migi pull request #10
Opened 2018-06-01 21:54 UTC by Sebastien-Ahkrin

I just adding a new decorator "autodelete" to deleting automatically a command.

like this : 
```js
export default function autodelete() {
	return (target, key, descriptor) => {
		const wrapped = descriptor.value
		descriptor.value = function(...fnargs) {
			fnargs[0].delete().catch(console.error)
			return wrapped.apply(this, fnargs)
		}
		return descriptor
	}
}
```
You can use this decorator with 
```js
@autodelete()
```
you need to add this to a command.

2018-06-01 21:57 UTC, DeltaEvo requested changes

2018-06-01 21:57 UTC, DeltaEvo commented on src/decorators/autodelete.js
> +            fnargs[0].delete().catch(console.error)
Remove `.catch(console.error)`

2018-06-01 21:58 UTC, DeltaEvo commented
Please rebase your changes on latest master, and squash your commits into only one :)

2018-06-02 14:06 UTC, DeltaEvo commented
Close #1

2018-06-02 14:13 UTC, cchudant submitted a review, later dismissed
You should use `Promise.all([fnargs[0].delete(), wrapped.apply(this, fnargs)` so that the promise rejection get caught if the bot lacks permission or if an unexpected error occurs (don't chain promises because we still want to call the command)

2018-06-02 15:27 UTC, LightDiscord commented
Maybe check if a message is deletable before deleting it?
```js
message.deletable && message.delete()
```

2018-06-05 15:04 UTC, DeltaEvo approved these changes

2018-06-05 15:04 UTC, merged